### ISSUE TITLE
Pywal css template has an error.

### ISSUE THREAD

**Issue by Arqamz** [Gremious/discord-wal-theme-template#6]
The pywall css template doesnt seem to be working for me.

Pywal Version: `wal 3.3.0`

Here's a screenshot of the error Im getting. 
![image](https://github.com/user-attachments/assets/61e3a495-d1f9-4336-addc-654dda243f38)

**Comment by Gremious** [comment]
Yep, check https://github.com/Gremious/discord-wal-theme-template/issues/2.
